import type { DomainPack } from "../types.js";
import { CLOUD_COMMODITY_RESOURCES, CLOUD_FIELD_LABELS, CLOUD_QUERY_SCHEMAS } from "./resources.js";
import { CLOUD_DETERMINISTIC_RULES, CLOUD_INTENT_CODE_INFERENCE } from "./deterministic-rules.js";
import { CLOUD_PERMISSION_RULES } from "./permission-rules.js";
import { CLOUD_TOOL_PERMISSION_POLICIES } from "./tool-permission-policies.js";
import { createCloudCommodityTools } from "./tools.js";
import { CLOUD_AGENTIC_FALLBACKS } from "./agentic-fallbacks.js";
import { cloudCommodityOpenUIPlugin } from "./surfaces/cloud-openui.js";
import { CLOUD_REPORT_COMPOSERS } from "./report-composer.js";

export const cloudCommodityPack: DomainPack = {
  id: "cloud_commodity",
  name: "云商品平台",
  version: "1.0.0",
  conflictPolicy: "error",
  description: "通用云商品平台业务域，覆盖产品商品化、Offer/SKU/计费项/价格、订单账单、发布审批、风险审查、经营估算和客户续约。",

  resources: CLOUD_COMMODITY_RESOURCES,
  tools: createCloudCommodityTools(),
  surfacePlugins: [cloudCommodityOpenUIPlugin],
  reportComposers: CLOUD_REPORT_COMPOSERS,
  agenticFallbacks: CLOUD_AGENTIC_FALLBACKS,
  deterministicRules: CLOUD_DETERMINISTIC_RULES,
  permissionRules: CLOUD_PERMISSION_RULES,
  toolPermissionPolicies: CLOUD_TOOL_PERMISSION_POLICIES,
  fieldLabels: CLOUD_FIELD_LABELS,
  querySchemas: CLOUD_QUERY_SCHEMAS,
  intentDir: "data/domains/cloud-commodity/intent-codes",
  intentCodeInferenceFns: CLOUD_INTENT_CODE_INFERENCE,

  intentCodeMappings: {
    cloud_products: "cloud.query.products",
    cloud_offers: "cloud.query.products",
    cloud_skus: "cloud.query.products",
    cloud_specs: "cloud.query.products",
    cloud_meters: "cloud.query.products",
    cloud_prices: "cloud.query.prices",
    cloud_regions: "cloud.query.products",
    cloud_customers: "cloud.query.renewals",
    cloud_contracts: "cloud.query.renewals",
    cloud_subscriptions: "cloud.query.renewals",
    cloud_orders: "cloud.query.products",
    cloud_bills: "cloud.query.billing",
    cloud_invoices: "cloud.query.billing",
    cloud_release_requests: "cloud.workflow.release_request",
    cloud_approval_tasks: "cloud.query.workflow_bottlenecks",
    cloud_risk_signals: "cloud.query.risks",
    cloud_workflow_tasks: "cloud.query.workflow_bottlenecks",
    cloud_renewal_opportunities: "cloud.query.renewals",
    cloud_operating_metrics: "cloud.query.operations",
    cloud_usage_estimators: "cloud.estimate.agent_plan_rounds",
    cloud_ipd_checkpoints: "cloud.ipd.readiness_review",
    cloud_productization_reviews: "cloud.productization.readiness_review",
    cloud_gtm_assets: "cloud.gtm.package_draft",
    cloud_entitlement_rules: "cloud.plan.entitlement_review",
    cloud_channel_publication_matrix: "cloud.channel.publication_review",
    cloud_sre_readiness_gates: "cloud.sre.launch_gate_review",
    cloud_master_data_lineage: "cloud.master_data.impact_review",
    cloud_financial_commercial_policies: "cloud.financial.commercialization_review",
    cloud_customer_explanation_playbooks: "cloud.customer.explanation",
    cloud_product_change_versions: "cloud.product_change.impact_review",
    cloud_post_launch_checks: "cloud.post_launch.health_check",
    cloud_capacity_pools: "cloud.capacity.risk_review",
    cloud_sales_opportunities: "cloud.solution.recommendation",
    cloud_sla_incidents: "cloud.ops.incident_impact",
    cloud_cost_simulations: "cloud.estimate.agent_plan_rounds",
    cloud_ai_models: "cloud.query.products",
    cloud_demo_scenarios: "cloud.query.products",
    cloud_source_refs: "cloud.query.products",
  },

  factKeyMappings: {
    cloud_products: "cloud_product_detail",
    cloud_prices: "cloud_price_detail",
    cloud_risk_signals: "cloud_risk_detail",
    cloud_workflow_tasks: "cloud_workflow_bottleneck_detail",
    cloud_renewal_opportunities: "cloud_renewal_detail",
    cloud_operating_metrics: "cloud_operating_metric_detail",
    cloud_ipd_checkpoints: "cloud_ipd_checkpoint_detail",
    cloud_productization_reviews: "cloud_productization_review_detail",
    cloud_entitlement_rules: "cloud_entitlement_rule_detail",
    cloud_channel_publication_matrix: "cloud_channel_publication_detail",
    cloud_sre_readiness_gates: "cloud_sre_launch_gate_detail",
    cloud_master_data_lineage: "cloud_master_data_lineage_detail",
    cloud_financial_commercial_policies: "cloud_financial_policy_detail",
    cloud_customer_explanation_playbooks: "cloud_customer_explanation_detail",
    cloud_product_change_versions: "cloud_product_change_version_detail",
    cloud_post_launch_checks: "cloud_post_launch_check_detail",
    cloud_capacity_pools: "cloud_capacity_pool_detail",
    cloud_sales_opportunities: "cloud_sales_opportunity_detail",
    cloud_sla_incidents: "cloud_sla_incident_detail",
  },

  toolLabels: {
    estimate_agent_plan_rounds: "Agent Plan 轮数估算",
    estimate_seedance_video_seconds: "Seedance 视频秒数估算",
    cloud_product_model_draft: "云商品配置草稿",
    cloud_productization_readiness_review: "云产品化定义评审",
    cloud_offer_design_review: "云商品 Offer 治理评审",
    cloud_plan_entitlement_review: "云套餐权益治理评审",
    cloud_channel_publication_review: "云商品渠道发布评审",
    cloud_sre_launch_gate_review: "云商品 SRE 上架门禁",
    cloud_master_data_impact_review: "云主数据变更影响评审",
    cloud_financial_commercialization_review: "云商品财务商业化评审",
    cloud_customer_explanation: "云客户解释话术",
    cloud_product_change_impact_review: "云商品版本变更影响评审",
    cloud_post_launch_health_check: "云商品发布后巡检",
    cloud_ipd_readiness_review: "云商品 IPD 就绪评审",
    cloud_gtm_package_draft: "云商品 GTM 包草稿",
    cloud_capacity_risk_review: "云商品容量风险评审",
    cloud_gmv_target_briefing: "云商品 GMV 目标简报",
    cloud_ops_incident_business_impact: "云商品运维事件经营影响",
    cloud_ops_degradation_plan: "云商品降级与通知方案",
    cloud_agent_plan_overage_policy: "Agent Plan 超额付费说明",
    cloud_retrospective_template: "云商品复盘模板",
    cloud_executive_briefing: "云商品经营简报",
    cloud_solution_recommendation: "云商品方案推荐",
    cloud_self_service_quote: "云商品自助询价",
    cloud_release_risk_review: "云商品发布风险审查",
    create_cloud_release_draft: "创建云商品发布草稿",
    create_cloud_approval_summary: "生成云商品审批摘要",
    simulate_cloud_closed_loop: "模拟云商品闭环",
  },

  toolCategories: {
    estimate_agent_plan_rounds: "compute",
    estimate_seedance_video_seconds: "compute",
    cloud_product_model_draft: "compute",
    cloud_productization_readiness_review: "compute",
    cloud_offer_design_review: "compute",
    cloud_plan_entitlement_review: "compute",
    cloud_channel_publication_review: "compute",
    cloud_sre_launch_gate_review: "compute",
    cloud_master_data_impact_review: "compute",
    cloud_financial_commercialization_review: "compute",
    cloud_customer_explanation: "compute",
    cloud_product_change_impact_review: "compute",
    cloud_post_launch_health_check: "compute",
    cloud_ipd_readiness_review: "compute",
    cloud_gtm_package_draft: "compute",
    cloud_capacity_risk_review: "compute",
    cloud_gmv_target_briefing: "compute",
    cloud_ops_incident_business_impact: "compute",
    cloud_ops_degradation_plan: "compute",
    cloud_agent_plan_overage_policy: "compute",
    cloud_retrospective_template: "compute",
    cloud_executive_briefing: "compute",
    cloud_solution_recommendation: "compute",
    cloud_self_service_quote: "compute",
    cloud_release_risk_review: "compute",
    create_cloud_release_draft: "compute",
    create_cloud_approval_summary: "compute",
    simulate_cloud_closed_loop: "compute",
  },

  catalogDomains: [
    { id: "cloud_commodity.catalog", label: "商品目录", description: "云产品、Offer、SKU、规格、计费项和地域", ownerDomain: "cloud_commodity" },
    { id: "cloud_commodity.billing", label: "计费与账单", description: "价格、订单、订购、账单、发票和合同折扣", ownerDomain: "cloud_commodity" },
    { id: "cloud_commodity.risk", label: "风险审查", description: "发布申请、审批任务、流程阻塞和风险信号", ownerDomain: "cloud_commodity" },
    { id: "cloud_commodity.estimation", label: "销售估算", description: "Agent Plan 轮数、Seedance 视频秒数和成本模拟", ownerDomain: "cloud_commodity" },
    { id: "cloud_commodity.ecs_story", label: "ECS 全链路演示", description: "IPD、GTM、容量、销售、运维事件和 GMV 目标闭环", ownerDomain: "cloud_commodity" },
  ],

  routerPromptHints: [
    "当用户提到云商品、云产品、产品能力、模型能力、产品化定义、权益、渠道发布、官网、控制台、Marketplace、云客户、SKU、Offer、计费项、价格、合同价、账单、发布申请、上线风险、审批、续约风险、Seedance、Agent Plan、AFP、视频生成预算、ECS、GPU、RDS、CLB、IPD、GTM、SLA、容量、限流、告警、灰度、回滚、SRE、运维事件或 GMV 目标时，应路由到 cloud_commodity 域。",
    "产品能力是否可产品化、产品化条件、产品定义交付物、能力边界、目标客户、成本输入和 SLA 初稿类问题优先使用 cloud_productization_readiness_review；不要把官网当成主数据来源。",
    "Offer/SKU/Meter/Price 关系、按量/包月/会员权益/超额付费是否能同时存在、折扣/促销/资源包互斥类问题优先使用 cloud_offer_design_review。",
    "Plan 型权益、会员每日赠送 Token、额度发放、消耗顺序、过期、退订、退款、超额付费、二次确认和账单解释类问题优先使用 cloud_plan_entitlement_review。",
    "官网、控制台、销售报价、API/Marketplace 各渠道展示字段、禁展示项、发布状态和来源口径类问题优先使用 cloud_channel_publication_review；官网是销售/营销渠道之一，不是商品主数据来源。",
    "Seedance 等自助购买上架前的容量、限流、告警、灰度、回滚、SLA、客服通知和销售同步门禁优先使用 cloud_sre_launch_gate_review。",
    "主数据字段归属、字段血缘、官网/控制台/销售/账单消费字段、修改 Offer 计费模式影响哪些对象类问题优先使用 cloud_master_data_impact_review。",
    "收入确认、递延收入、免费额度成本归集、资源包收入确认、折扣叠加、毛利底线和财务口径类问题优先使用 cloud_financial_commercialization_review。",
    "客户问额度用完是否自动扣费、账单为什么高于估算、赠送 Token 为什么过期、估算是否正式报价类问题优先使用 cloud_customer_explanation，必须输出客户友好的解释和必须披露边界。",
    "已有商品变更、套餐额度调整、新增/下线 SKU、Offer 改名、价格调整、权益调整、地域扩容、存量客户影响和合同兼容性类问题优先使用 cloud_product_change_impact_review。",
    "发布后 24 小时巡检、官网/控制台/销售报价一致性、订单/计量/账单闭环校验、客户反馈和发布健康日报类问题优先使用 cloud_post_launch_health_check。",
    "ECS GPU 全链路演示中，IPD/PRD/购买页字段/上架检查类问题优先使用 cloud_ipd_readiness_review；GTM/销售话术/FAQ/不可承诺项优先使用 cloud_gtm_package_draft；容量/SRE/限售/灰度优先使用 cloud_capacity_risk_review；GMV 目标/达成/经营健康优先使用 cloud_gmv_target_briefing；运维事件/交付延期/客户沟通/回滚优先使用 cloud_ops_incident_business_impact；事故降级、队列健康、失败率上升、客服通知优先使用 cloud_ops_degradation_plan；复盘成模板优先使用 cloud_retrospective_template。",
    "Agent Plan 额度用完、自动扣费、超额付费和二次确认类问题优先使用 cloud_agent_plan_overage_policy，必须明确不会自动扣费、由客户管理员确认后才开通。",
    "销售估算类问题必须使用专用估算工具，并输出公式、假设、证据、置信度和边界，不能承诺固定产能。",
    "老板/管理者类风险问题优先查询 cloud_risk_signals、cloud_workflow_tasks 和 cloud_renewal_opportunities，回答要给排序、影响、负责人和下一步动作。",
    "老板/管理者类经营问题还应纳入 cloud_operating_metrics，回答 GMV、净收入、毛利率、活跃客户、续约风险金额和发布阻塞等经营指标。",
    "云账单、发票、账期、争议金额类问题应路由到 cloud.query.billing，并按客户可见范围隔离。",
    "云商品发布、价格、促销、退订、上架类动作只能生成草稿、审批摘要或闭环模拟，不得声称已经真实生效。",
  ],

  answerPromptHints: [
    "云商品回答必须区分官方事实、公开报道、mock 数据和 demo 假设；包含 mocked/source_type/demo_assumption 的内容不得表达为官方承诺。",
    "云商品回答不要暴露研发态字段名或内部ID；owner_user_id、owner_team、metric_id、source_type 等字段要转写成中文业务词，finance_reviewer_001 要说“财务复核负责人”，legal_001 要说“法务审核负责人”，ai_business 要说“AI 商品经营团队”，cloud_business 要说“云业务经营团队”。",
    "云商品回答不要把筛选条件当成结论输出；禁止写 severity=high、delay_hours>0、arr_at_risk_cny、cloud_operating_metrics、cloud_risk_signals 等工程表达。应写成“高严重度风险”“已延期阻塞项”“续约风险金额”“经营指标、风险信号、流程任务、续约机会”。",
    "当用户问产品化时，应先解释这是“技术/模型能力变成合格产品定义”的阶段，输出目标客户、价值主张、交付物、能力边界、成本输入、SLA 初稿、负责人和后续动作。",
    "当用户问渠道时，应明确商品主数据来自商品中台；官网、控制台、销售报价、API/Marketplace 是不同触点，官网虽然可获客和销售转化，但不是主数据来源。",
    "当用户问 Plan 型权益时，应明确额度发放、消耗顺序、过期、退订、退款、超额付费、二次确认和账单解释，不能让客户误以为赠送额度等于现金或会自动扣费。",
    "当用户问主数据治理时，应输出主数据源、字段归属方、下游消费系统、影响对象、必做检查和人工确认边界。",
    "当用户问财务商业化时，应区分收入确认、成本归集、递延收入、折扣叠加和毛利底线；所有内容只能作为演示口径，不代表正式会计政策。",
    "当用户问客户解释时，应使用客户能听懂的话，不暴露内部成本、毛利底线、模型路由、风控阈值等内部字段。",
    "当用户问商品变更或发布后巡检时，应输出影响客户/合同/账单/渠道、回滚计划、负责人和后续动作；不得表现为已经完成生产变更。",
    "云商品老板简报的“下一步动作”必须是清晰动作清单，每条包含对象/负责人/动作/时间或目标；不要写字段判断、资源名、查询条件或后台表名。",
    "销售估算回答必须包含公式、关键假设、敏感因素、置信度和边界说明。",
    "销售解决方案回答必须包含预算拆分、组合理由、关键假设、报价边界和置信度，不得把 demo 预算拆分说成固定报价。",
    "ECS GPU 回答必须把 IPD、容量、SLA、折扣、交付、GMV 和客户沟通串成业务闭环；不得承诺真实库存、正式价格、固定交付日期或固定算力可用性。",
    "风险审查回答必须包含风险等级、风险项、阻塞任务、影响客户、建议动作、人审标记和回滚检查点。",
    "对外售卖演示时，应称为通用云商品平台能力；火山引擎只是 demo provider，不要把 domain 能力写死为某一家云厂商。",
  ],

  dataQueryKeywords: [
    "云商品", "云产品", "产品能力", "模型能力", "产品化", "产品定义", "主数据", "血缘", "字段归属", "下游系统", "收入确认", "递延收入", "客户解释", "版本变更", "发布后巡检", "权益", "渠道发布", "官网", "控制台", "Marketplace", "SKU", "Offer", "计费项", "价格", "合同价", "账单", "订购", "发票",
    "发布申请", "审批任务", "上线风险", "流程阻塞", "续约", "续约风险", "云客户", "经营指标", "GMV", "毛利", "净收入", "活跃客户", "Seedance", "Agent Plan", "AFP",
    "ECS", "GPU", "RDS", "CLB", "IPD", "GTM", "SLA", "容量", "SRE", "运维事件", "交付延期", "目标达成", "限流", "告警", "灰度", "回滚", "客服通知", "超额付费", "二次确认", "复盘模板",
  ],

  classificationKeywords: {
    data_query: [
      "云商品", "云产品", "产品能力", "模型能力", "产品化", "产品定义", "主数据", "血缘", "字段归属", "下游系统", "收入确认", "递延收入", "客户解释", "版本变更", "发布后巡检", "权益", "渠道发布", "官网", "控制台", "Marketplace", "SKU", "Offer", "计费项", "价格", "合同价", "账单", "订购", "发票",
      "风险", "阻塞", "审批", "续约", "续约风险", "云客户", "经营指标", "GMV", "毛利", "净收入", "活跃客户", "Seedance", "Agent Plan", "AFP",
      "ECS", "GPU", "RDS", "CLB", "IPD", "GTM", "SLA", "容量", "运维事件", "交付延期", "目标达成",
    ],
  },

  capabilityDescriptions: [
    "查询云商品平台产品、Offer、SKU、计费项、价格、订购、账单和审批数据",
    "估算 Agent Plan 对话轮数和 Seedance 视频生成预算产能",
    "生成云商品配置草稿、发布风险审查、审批摘要和闭环模拟计划",
    "评审产品能力是否可产品化，治理 Offer/SKU/计量/价格关系、Plan 型权益、渠道发布矩阵和 SRE 上架门禁",
    "评审主数据血缘、字段变更影响、财务商业化口径、客户解释、商品版本变更和发布后巡检",
    "演示 ECS GPU 从 IPD、商品上架、GTM、销售方案、运维事件到 GMV 目标达成的多角色协同闭环",
  ],

  standaloneTaskKeywords: [
    "云商品", "云产品", "产品能力", "产品化", "主数据", "血缘", "收入确认", "客户解释", "版本变更", "发布后巡检", "权益", "渠道发布", "官网", "控制台", "云客户", "SKU", "Offer", "计费", "价格", "账单", "发布", "审批", "风险", "续约", "续约风险", "Seedance", "Agent Plan", "ECS", "GPU", "IPD", "GTM", "SLA", "容量", "SRE", "运维",
  ],
};
