import type { FieldLabels, ResourceConfig } from "../../resources/types.js";
import { loadJson } from "../../data/load-json.js";

type DataRow = Record<string, unknown>;

function cloudResource(
  file: string,
  fields: string[],
  label: string,
  options: Partial<ResourceConfig> = {},
): ResourceConfig {
  return {
    file: `data/cloud-commodity/${file}`,
    fields,
    domain: "cloud_commodity",
    label,
    defaultLimit: 20,
    ...options,
  };
}

function cloudRow(idField: string, nameField: string, extraFields: string[] = []) {
  return (row: DataRow) => {
    const extras = extraFields
      .map((field) => row[field] == null ? "" : `${CLOUD_FIELD_LABELS[field] ?? field} ${row[field]}`)
      .filter(Boolean)
      .join("，");
    return `- [${row[idField] ?? ""}] ${row[nameField] ?? ""}${extras ? `（${extras}）` : ""}`;
  };
}

async function loadCloudSampleAgentAnswers(): Promise<DataRow[]> {
  const data = await loadJson<Record<string, unknown>>("data/cloud-commodity/cloud_sample_agent_answers.json");
  const rows: DataRow[] = [];
  for (const [sampleGroup, value] of Object.entries(data)) {
    const items = Array.isArray(value) ? value : [value];
    items.forEach((item, index) => {
      if (!item || typeof item !== "object" || Array.isArray(item)) return;
      rows.push({
        sample_id: items.length > 1 ? `${sampleGroup}_${index + 1}` : sampleGroup,
        sample_group: sampleGroup,
        ...(item as DataRow),
      });
    });
  }
  return rows;
}

export const CLOUD_COMMODITY_RESOURCES: Record<string, ResourceConfig> = {
  cloud_products: cloudResource(
    "cloud_products.json",
    ["product_id", "product_code", "product_name", "provider", "product_family_id", "product_category", "lifecycle_status", "console_url", "docs_url", "source_ref_ids"],
    "云产品主数据",
    {
      displayColumns: [["product_code", "产品代码"], ["product_name", "产品名称"], ["provider", "云厂商"], ["product_category", "分类"], ["lifecycle_status", "生命周期"]],
      debugFields: ["product_id", "product_code", "product_name", "provider", "product_category", "source_ref_ids"],
      factKey: "cloud_product_detail",
      rowTemplate: cloudRow("product_id", "product_name", ["product_code", "provider", "product_category"]),
    },
  ),
  cloud_offers: cloudResource(
    "cloud_offers.json",
    ["offer_id", "product_id", "offer_code", "offer_name", "billing_mode", "purchase_mode", "renewal_supported", "refund_supported", "resize_supported", "source_ref_ids"],
    "云商品 Offer",
    {
      displayColumns: [["offer_name", "Offer"], ["billing_mode", "计费模式"], ["purchase_mode", "购买模式"], ["renewal_supported", "支持续费"], ["refund_supported", "支持退款"]],
      debugFields: ["offer_id", "product_id", "offer_name", "billing_mode", "purchase_mode"],
      rowTemplate: cloudRow("offer_id", "offer_name", ["billing_mode", "purchase_mode"]),
    },
  ),
  cloud_skus: cloudResource(
    "cloud_skus.json",
    ["sku_id", "product_id", "offer_id", "sku_code", "sku_name", "sku_family", "status", "source_ref_ids"],
    "云商品 SKU",
    {
      displayColumns: [["sku_name", "SKU"], ["sku_family", "规格族"], ["status", "状态"], ["product_id", "产品"], ["offer_id", "Offer"]],
      debugFields: ["sku_id", "product_id", "offer_id", "sku_name", "sku_family", "status"],
      rowTemplate: cloudRow("sku_id", "sku_name", ["sku_family", "status"]),
    },
  ),
  cloud_specs: cloudResource(
    "cloud_specs.json",
    ["spec_id", "sku_id", "spec_key", "spec_name", "spec_value", "spec_unit", "value_type", "required_for_purchase"],
    "云商品规格维度",
    { displayColumns: [["sku_id", "SKU"], ["spec_name", "规格"], ["spec_value", "值"], ["spec_unit", "单位"], ["required_for_purchase", "购买必填"]] },
  ),
  cloud_meters: cloudResource(
    "cloud_meters.json",
    ["meter_id", "product_id", "meter_code", "meter_name", "meter_unit", "metering_granularity", "billing_dimension"],
    "云商品计费项",
    { displayColumns: [["meter_name", "计费项"], ["meter_unit", "单位"], ["metering_granularity", "粒度"], ["billing_dimension", "计费维度"]] },
  ),
  cloud_prices: cloudResource(
    "cloud_prices.json",
    ["price_id", "offer_id", "sku_id", "meter_id", "region_id", "currency", "price_type", "unit_price", "pricing_rule", "source_ref_ids"],
    "云商品价格规则",
    {
      displayColumns: [["sku_id", "SKU"], ["meter_id", "计费项"], ["region_id", "地域"], ["price_type", "价格类型"], ["unit_price", "单价"]],
      debugFields: ["price_id", "offer_id", "sku_id", "meter_id", "region_id", "unit_price", "source_ref_ids"],
      rowTemplate: cloudRow("price_id", "sku_id", ["meter_id", "region_id", "unit_price"]),
    },
  ),
  cloud_regions: cloudResource(
    "cloud_regions.json",
    ["region_id", "region_code", "region_name", "country", "availability_zone_count", "supported_product_codes"],
    "云地域",
    { displayColumns: [["region_code", "地域代码"], ["region_name", "地域名称"], ["country", "国家/区域"], ["availability_zone_count", "可用区数"]] },
  ),
  cloud_product_families: cloudResource(
    "cloud_product_families.json",
    ["family_id", "family_name", "category", "description"],
    "云产品族",
    {
      displayColumns: [["family_name", "产品族"], ["category", "分类"], ["description", "说明"]],
      debugFields: ["family_id", "family_name", "category"],
      rowTemplate: cloudRow("family_id", "family_name", ["category"]),
    },
  ),
  cloud_customers: cloudResource(
    "cloud_customers.json",
    ["customer_id", "customer_name", "industry", "tier", "account_owner", "budget_cny", "cost_center_ids", "source_ref_ids"],
    "云企业客户",
    {
      scopeField: "customer_id",
      userScopeField: "accessible_customer_ids",
      displayColumns: [["customer_name", "客户"], ["industry", "行业"], ["tier", "等级"], ["account_owner", "负责人"], ["budget_cny", "预算"]],
      debugFields: ["customer_id", "customer_name", "tier", "budget_cny"],
      rowTemplate: cloudRow("customer_id", "customer_name", ["tier", "budget_cny"]),
    },
  ),
  cloud_accounts: cloudResource(
    "cloud_accounts.json",
    ["account_id", "customer_id", "account_type", "display_name", "budget_cny", "parent_account_id"],
    "云客户账户",
    {
      scopeField: "customer_id",
      userScopeField: "accessible_customer_ids",
      displayColumns: [["display_name", "账户"], ["customer_id", "客户"], ["account_type", "账户类型"], ["budget_cny", "预算"]],
      debugFields: ["account_id", "customer_id", "account_type", "parent_account_id"],
      rowTemplate: cloudRow("account_id", "display_name", ["account_type", "budget_cny"]),
    },
  ),
  cloud_contracts: cloudResource(
    "cloud_contracts.json",
    ["contract_id", "customer_id", "contract_name", "effective_date", "expire_date", "discount_policy", "invoice_title"],
    "云客户合同",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["contract_name", "合同"], ["customer_id", "客户"], ["effective_date", "生效日"], ["expire_date", "到期日"]] },
  ),
  cloud_subscriptions: cloudResource(
    "cloud_subscriptions.json",
    ["subscription_id", "customer_id", "order_id", "offer_id", "sku_id", "status", "start_at", "end_at", "renewal_status"],
    "云订购关系",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["subscription_id", "订购"], ["customer_id", "客户"], ["sku_id", "SKU"], ["status", "状态"], ["renewal_status", "续约状态"]] },
  ),
  cloud_orders: cloudResource(
    "cloud_orders.json",
    ["order_id", "customer_id", "account_id", "order_status", "payment_status", "created_at", "total_amount_cny", "source_ref_ids"],
    "云商品订单",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["order_id", "订单"], ["customer_id", "客户"], ["order_status", "订单状态"], ["payment_status", "支付状态"], ["total_amount_cny", "金额"]] },
  ),
  cloud_order_items: cloudResource(
    "cloud_order_items.json",
    ["order_item_id", "order_id", "offer_id", "sku_id", "quantity", "amount_cny", "source_type", "mocked", "confidence"],
    "云订单明细",
    {
      displayColumns: [["order_item_id", "明细"], ["order_id", "订单"], ["sku_id", "SKU"], ["quantity", "数量"], ["amount_cny", "金额"]],
      debugFields: ["order_item_id", "order_id", "offer_id", "sku_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("order_item_id", "sku_id", ["quantity", "amount_cny"]),
    },
  ),
  cloud_bills: cloudResource(
    "cloud_bills.json",
    ["bill_id", "customer_id", "billing_month", "status", "amount_cny", "source_metering_record_ids"],
    "云账单",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["bill_id", "账单"], ["customer_id", "客户"], ["billing_month", "账期"], ["status", "状态"], ["amount_cny", "金额"]] },
  ),
  cloud_invoices: cloudResource(
    "cloud_invoices.json",
    ["invoice_id", "bill_id", "customer_id", "invoice_title", "status", "amount_cny"],
    "云发票",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["invoice_id", "发票"], ["invoice_title", "抬头"], ["status", "状态"], ["amount_cny", "金额"]] },
  ),
  cloud_release_requests: cloudResource(
    "cloud_release_requests.json",
    ["release_request_id", "product_id", "title", "change_type", "status", "requested_by", "rollback_plan", "source_ref_ids"],
    "云商品发布申请",
    { displayColumns: [["release_request_id", "申请"], ["title", "标题"], ["change_type", "变更类型"], ["status", "状态"], ["rollback_plan", "回滚方案"]] },
  ),
  cloud_approval_tasks: cloudResource(
    "cloud_approval_tasks.json",
    ["approval_task_id", "release_request_id", "approver_role", "assignee", "status", "reason"],
    "云商品审批任务",
    { displayColumns: [["approval_task_id", "审批"], ["release_request_id", "发布申请"], ["approver_role", "审批角色"], ["assignee", "处理人"], ["status", "状态"], ["reason", "原因"]] },
  ),
  cloud_risk_signals: cloudResource(
    "cloud_risk_signals.json",
    ["risk_signal_id", "risk_type", "title", "severity", "linked_entities", "evidence", "detected_at", "owner_team", "recommended_actions", "mocked"],
    "云商品风险信号",
    { displayColumns: [["title", "风险"], ["severity", "严重度"], ["risk_type", "类型"], ["owner_team", "负责人团队"], ["detected_at", "发现时间"]] },
  ),
  cloud_workflow_tasks: cloudResource(
    "cloud_workflow_tasks.json",
    ["task_id", "workflow_id", "linked_release_request_id", "step", "owner_user_id", "owner_team", "status", "submitted_at", "due_at", "completed_at", "sla_hours", "delay_hours", "blocker_reason", "impact", "mocked"],
    "云商品流程任务",
    { displayColumns: [["step", "环节"], ["owner_team", "负责团队"], ["status", "状态"], ["delay_hours", "延迟小时"], ["blocker_reason", "阻塞原因"]] },
  ),
  cloud_metering_records: cloudResource(
    "cloud_metering_records.json",
    ["metering_record_id", "subscription_id", "meter_id", "measured_at", "quantity", "unit", "source", "source_type", "mocked", "confidence"],
    "云用量计量记录",
    {
      displayColumns: [["metering_record_id", "计量记录"], ["subscription_id", "订购"], ["meter_id", "计费项"], ["quantity", "用量"], ["unit", "单位"]],
      debugFields: ["metering_record_id", "subscription_id", "meter_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("metering_record_id", "meter_id", ["quantity", "unit"]),
    },
  ),
  cloud_renewal_opportunities: cloudResource(
    "cloud_renewal_opportunities.json",
    ["renewal_id", "customer_id", "contract_id", "owner_user_id", "renewal_due_date", "current_arr_cny", "forecast_next_arr_cny", "renewal_probability", "risk_level", "risk_reasons", "recommended_actions", "mocked"],
    "云客户续约机会",
    { scopeField: "customer_id", userScopeField: "accessible_customer_ids", displayColumns: [["renewal_id", "续约"], ["customer_id", "客户"], ["forecast_next_arr_cny", "预测ARR"], ["renewal_probability", "续约概率"], ["risk_level", "风险等级"]] },
  ),
  cloud_operating_metrics: cloudResource(
    "cloud_operating_metrics.json",
    ["metric_id", "period", "as_of_date", "metric_group", "metric_name", "metric_value", "unit", "compare_period", "compare_value", "change_rate", "product_id", "customer_id", "owner_team", "status", "insight", "recommended_actions", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品经营指标",
    {
      scopeField: "customer_id",
      userScopeField: "accessible_customer_ids",
      displayColumns: [["metric_name", "指标"], ["metric_value", "数值"], ["unit", "单位"], ["change_rate", "变化率"], ["owner_team", "负责团队"], ["status", "状态"], ["insight", "洞察"]],
      debugFields: ["metric_id", "period", "metric_group", "metric_name", "product_id", "customer_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("metric_id", "metric_name", ["metric_value", "unit", "change_rate", "status"]),
    },
  ),
  cloud_metric_definitions: cloudResource(
    "cloud_metric_definitions.json",
    ["metric_id", "name", "owner", "grain", "formula", "source_entities", "boss_relevance"],
    "云经营指标定义",
    {
      displayColumns: [["name", "指标"], ["owner", "口径负责人"], ["grain", "统计粒度"], ["formula", "计算公式"], ["boss_relevance", "老板视角价值"]],
      debugFields: ["metric_id", "name", "owner", "source_entities"],
      rowTemplate: cloudRow("metric_id", "name", ["grain", "owner"]),
    },
  ),
  cloud_metric_snapshots: cloudResource(
    "cloud_metric_snapshots.json",
    ["snapshot_id", "metric_id", "period", "dimensions", "value", "unit", "trend", "mocked"],
    "云经营指标快照",
    {
      displayColumns: [["metric_id", "指标"], ["period", "周期"], ["value", "数值"], ["unit", "单位"], ["trend", "趋势"], ["mocked", "数据性质"]],
      debugFields: ["snapshot_id", "metric_id", "period", "dimensions", "mocked"],
      rowTemplate: cloudRow("snapshot_id", "metric_id", ["period", "value", "unit"]),
    },
  ),
  cloud_usage_estimators: cloudResource(
    "cloud_usage_estimators.json",
    ["estimator_id", "product_id", "offer_id", "estimator_type", "input_params_schema", "formula", "assumptions", "caveat", "source_ref_ids"],
    "云商品估算器",
    { displayColumns: [["estimator_id", "估算器"], ["product_id", "产品"], ["estimator_type", "类型"], ["formula", "公式"], ["caveat", "边界说明"]] },
  ),
  cloud_ipd_checkpoints: cloudResource(
    "cloud_ipd_checkpoints.json",
    ["checkpoint_id", "product_id", "release_request_id", "stage", "checkpoint_name", "status", "owner_team", "owner_user_id", "evidence", "gap", "next_action", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品 IPD 检查点",
    {
      displayColumns: [["stage", "阶段"], ["checkpoint_name", "检查点"], ["status", "状态"], ["owner_team", "负责团队"], ["gap", "缺口"], ["next_action", "下一步"]],
      debugFields: ["checkpoint_id", "product_id", "release_request_id", "status", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("checkpoint_id", "checkpoint_name", ["stage", "status", "owner_team"]),
    },
  ),
  cloud_productization_reviews: cloudResource(
    "cloud_productization_reviews.json",
    ["review_id", "product_id", "product_name", "capability_name", "capability_stage", "overall_status", "readiness_score", "target_customers", "value_proposition", "deliverables", "boundary_items", "cost_inputs", "sla_draft", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云产品化定义评审",
    {
      displayColumns: [["product_name", "产品"], ["capability_name", "能力"], ["capability_stage", "阶段"], ["overall_status", "状态"], ["readiness_score", "就绪度"]],
      debugFields: ["review_id", "product_id", "overall_status", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("review_id", "product_name", ["capability_stage", "overall_status", "readiness_score"]),
    },
  ),
  cloud_gtm_assets: cloudResource(
    "cloud_gtm_assets.json",
    ["asset_id", "product_id", "asset_type", "title", "audience", "content", "owner_team", "status", "not_to_commit", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品 GTM 材料",
    {
      displayColumns: [["title", "材料"], ["asset_type", "类型"], ["audience", "受众"], ["status", "状态"], ["owner_team", "负责团队"], ["not_to_commit", "不可承诺项"]],
      debugFields: ["asset_id", "product_id", "asset_type", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("asset_id", "title", ["asset_type", "status"]),
    },
  ),
  cloud_entitlement_rules: cloudResource(
    "cloud_entitlement_rules.json",
    ["rule_id", "product_id", "offer_id", "entitlement_name", "grant_rule", "consume_order", "expiry_rule", "unsubscribe_rule", "refund_rule", "overage_policy", "confirmation_required", "billing_explanation", "risk_level", "owner", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云套餐权益规则",
    {
      displayColumns: [["entitlement_name", "权益"], ["grant_rule", "发放规则"], ["consume_order", "消耗顺序"], ["overage_policy", "超额策略"], ["risk_level", "风险等级"]],
      debugFields: ["rule_id", "product_id", "offer_id", "risk_level", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("rule_id", "entitlement_name", ["risk_level", "owner"]),
    },
  ),
  cloud_channel_publication_matrix: cloudResource(
    "cloud_channel_publication_matrix.json",
    ["matrix_id", "product_id", "product_name", "channel", "channel_purpose", "visible_fields", "hidden_fields", "source_of_truth", "publication_status", "owner", "precheck", "boundary_note", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品渠道发布矩阵",
    {
      displayColumns: [["channel", "渠道"], ["channel_purpose", "渠道目的"], ["publication_status", "发布状态"], ["owner", "负责人"], ["precheck", "发布前检查"]],
      debugFields: ["matrix_id", "product_id", "channel", "publication_status", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("matrix_id", "channel", ["publication_status", "owner"]),
    },
  ),
  cloud_sre_readiness_gates: cloudResource(
    "cloud_sre_readiness_gates.json",
    ["gate_id", "product_id", "release_request_id", "gate_name", "status", "owner", "metric", "threshold", "risk_if_missing", "next_action", "rollback_trigger", "customer_notice", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品 SRE 上架门禁",
    {
      displayColumns: [["gate_name", "门禁"], ["status", "状态"], ["owner", "负责人"], ["metric", "观察指标"], ["next_action", "后续动作"]],
      debugFields: ["gate_id", "product_id", "release_request_id", "status", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("gate_id", "gate_name", ["status", "owner"]),
    },
  ),
  cloud_capacity_pools: cloudResource(
    "cloud_capacity_pools.json",
    ["capacity_pool_id", "product_id", "region_id", "region_name", "sku_family", "total_gpu_cards", "reserved_gpu_cards", "available_gpu_cards", "peak_commitment_ratio", "health_status", "sales_policy", "owner_team", "next_action", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品容量池",
    {
      displayColumns: [["region_name", "地域"], ["sku_family", "规格族"], ["available_gpu_cards", "可用 GPU 卡"], ["peak_commitment_ratio", "峰值覆盖率"], ["health_status", "健康度"], ["sales_policy", "销售策略"]],
      debugFields: ["capacity_pool_id", "product_id", "region_id", "health_status", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("capacity_pool_id", "region_name", ["available_gpu_cards", "peak_commitment_ratio", "health_status"]),
    },
  ),
  cloud_sales_opportunities: cloudResource(
    "cloud_sales_opportunities.json",
    ["opportunity_id", "customer_id", "customer_name", "industry", "product_ids", "budget_cny", "stage", "probability", "expected_close_month", "decision_maker", "region_preference", "requirements", "blockers", "recommended_solution", "next_action", "owner_user_id", "owner_team", "weighted_pipeline_cny", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品销售商机",
    {
      scopeField: "customer_id",
      userScopeField: "accessible_customer_ids",
      displayColumns: [["customer_name", "客户"], ["industry", "行业"], ["budget_cny", "预算"], ["stage", "阶段"], ["probability", "成交概率"], ["weighted_pipeline_cny", "加权商机"]],
      debugFields: ["opportunity_id", "customer_id", "product_ids", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("opportunity_id", "customer_name", ["budget_cny", "stage", "weighted_pipeline_cny"]),
    },
  ),
  cloud_sla_incidents: cloudResource(
    "cloud_sla_incidents.json",
    ["incident_id", "product_id", "region_id", "title", "severity", "status", "started_at", "expected_recovery_at", "delay_hours", "affected_order_ids", "affected_customer_ids", "impact_gmv_cny", "revenue_recognition_risk_cny", "customer_impact", "root_cause", "mitigation_steps", "rollback_plan", "owner_team", "owner_user_id", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品 SLA/运维事件",
    {
      displayColumns: [["title", "事件"], ["severity", "严重度"], ["status", "状态"], ["delay_hours", "延期小时"], ["impact_gmv_cny", "影响 GMV"], ["owner_team", "负责团队"]],
      debugFields: ["incident_id", "product_id", "region_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("incident_id", "title", ["severity", "status", "impact_gmv_cny"]),
    },
  ),
  cloud_cost_simulations: cloudResource(
    "cloud_cost_simulations.json",
    ["simulation_id", "estimator_id", "input", "output", "evidence_refs", "confidence", "mocked"],
    "云商品成本模拟",
    { displayColumns: [["simulation_id", "模拟"], ["estimator_id", "估算器"], ["confidence", "置信度"], ["mocked", "Demo假设"]] },
  ),
  cloud_risk_rules: cloudResource(
    "cloud_risk_rules.json",
    ["risk_rule_id", "rule_name", "severity", "target_table", "suggested_action"],
    "云风险规则",
    {
      displayColumns: [["rule_name", "规则"], ["severity", "严重度"], ["target_table", "适用对象"], ["suggested_action", "建议动作"]],
      debugFields: ["risk_rule_id", "target_table", "severity"],
      rowTemplate: cloudRow("risk_rule_id", "rule_name", ["severity", "target_table"]),
    },
  ),
  cloud_assumption_profiles: cloudResource(
    "cloud_assumption_profiles.json",
    ["assumption_profile_id", "name", "applies_to_products", "assumptions", "caveat", "source_type"],
    "云估算假设口径",
    {
      displayColumns: [["name", "假设口径"], ["applies_to_products", "适用产品"], ["assumptions", "关键假设"], ["caveat", "边界说明"]],
      debugFields: ["assumption_profile_id", "applies_to_products", "source_type"],
      rowTemplate: cloudRow("assumption_profile_id", "name", ["source_type"]),
    },
  ),
  cloud_ai_models: cloudResource(
    "cloud_ai_models.json",
    ["ai_model_id", "product_id", "model_name", "modality", "input_unit", "output_unit", "max_context", "supported_scenarios", "source_ref_ids"],
    "AI 模型目录",
    { displayColumns: [["model_name", "模型"], ["modality", "模态"], ["input_unit", "输入单位"], ["output_unit", "输出单位"], ["max_context", "上下文"]] },
  ),
  cloud_demo_scenarios: cloudResource(
    "cloud_demo_scenarios.json",
    ["scenario_id", "persona", "user_question", "scenario_type", "product_id", "expected_output", "source_ref_ids"],
    "云商品演示场景",
    { displayColumns: [["scenario_id", "场景"], ["persona", "角色"], ["scenario_type", "类型"], ["user_question", "用户问题"]] },
  ),
  cloud_answer_playbooks: cloudResource(
    "cloud_answer_playbooks.json",
    ["playbook_id", "audience", "user_question", "route", "must_include", "example_answer"],
    "云回答策略样例",
    {
      displayColumns: [["audience", "面向角色"], ["user_question", "用户问题"], ["route", "建议路由"], ["must_include", "必须包含"]],
      debugFields: ["playbook_id", "audience", "route"],
      rowTemplate: cloudRow("playbook_id", "user_question", ["audience", "route"]),
    },
  ),
  cloud_data_contracts: cloudResource(
    "cloud_data_contracts.json",
    ["contract_id", "name", "required_fields", "forbidden_behavior"],
    "云数据回答契约",
    {
      displayColumns: [["name", "契约"], ["required_fields", "必含信息"], ["forbidden_behavior", "禁止行为"]],
      debugFields: ["contract_id", "name"],
      rowTemplate: cloudRow("contract_id", "name"),
    },
  ),
  cloud_master_data_lineage: cloudResource(
    "cloud_master_data_lineage.json",
    ["lineage_id", "product_id", "entity_name", "field_name", "business_label", "owner_system", "owner_role", "source_of_truth", "downstream_systems", "consumed_by", "change_risk", "change_impact", "required_checks", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云主数据血缘",
    {
      displayColumns: [["business_label", "业务字段"], ["owner_system", "主数据系统"], ["downstream_systems", "下游系统"], ["change_risk", "变更风险"], ["change_impact", "变更影响"]],
      debugFields: ["lineage_id", "product_id", "field_name", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("lineage_id", "business_label", ["owner_system", "change_risk"]),
    },
  ),
  cloud_financial_commercial_policies: cloudResource(
    "cloud_financial_commercial_policies.json",
    ["policy_id", "product_id", "policy_name", "commercial_model", "revenue_recognition", "cost_allocation", "deferred_revenue_rule", "discount_stack_rule", "gross_margin_floor", "approval_required_when", "risk_level", "owner", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品财务商业化口径",
    {
      displayColumns: [["policy_name", "财务口径"], ["commercial_model", "商业模式"], ["gross_margin_floor", "毛利底线"], ["risk_level", "风险等级"], ["owner", "负责人"]],
      debugFields: ["policy_id", "product_id", "risk_level", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("policy_id", "policy_name", ["commercial_model", "risk_level"]),
    },
  ),
  cloud_customer_explanation_playbooks: cloudResource(
    "cloud_customer_explanation_playbooks.json",
    ["playbook_id", "product_id", "scenario", "customer_question", "plain_answer", "must_disclose", "visible_fields", "hidden_fields", "next_action", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云客户解释话术",
    {
      displayColumns: [["scenario", "场景"], ["customer_question", "客户问题"], ["plain_answer", "客户友好解释"], ["must_disclose", "必须披露"], ["next_action", "后续动作"]],
      debugFields: ["playbook_id", "product_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("playbook_id", "scenario", ["product_id"]),
    },
  ),
  cloud_product_change_versions: cloudResource(
    "cloud_product_change_versions.json",
    ["change_id", "product_id", "change_type", "title", "current_version", "target_version", "change_summary", "affected_entities", "affected_customers", "contract_compatibility", "channel_sync_required", "rollback_plan", "approval_status", "risk_level", "owner", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品版本变更",
    {
      displayColumns: [["title", "变更"], ["change_type", "类型"], ["target_version", "目标版本"], ["risk_level", "风险等级"], ["approval_status", "审批状态"]],
      debugFields: ["change_id", "product_id", "current_version", "target_version", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("change_id", "title", ["change_type", "risk_level"]),
    },
  ),
  cloud_post_launch_checks: cloudResource(
    "cloud_post_launch_checks.json",
    ["check_id", "product_id", "release_request_id", "check_window", "check_area", "check_item", "status", "finding", "impact", "owner", "next_action", "source_type", "mocked", "confidence", "source_ref_ids"],
    "云商品发布后巡检",
    {
      displayColumns: [["check_area", "巡检域"], ["check_item", "检查项"], ["status", "状态"], ["finding", "发现"], ["next_action", "后续动作"]],
      debugFields: ["check_id", "product_id", "release_request_id", "source_type", "mocked", "confidence"],
      rowTemplate: cloudRow("check_id", "check_item", ["status", "owner"]),
    },
  ),
  cloud_sample_agent_answers: cloudResource(
    "cloud_sample_agent_answers.json",
    [
      "sample_id", "sample_group", "estimated_rounds", "effective_afp", "estimated_afp_per_round", "recommended_plan", "explanation",
      "estimated_video_seconds", "estimated_video_count_5s", "unit_cost_per_second_cny", "token_cost_cny", "storage_cdn_cost_estimate_cny", "safety_buffer_cny",
      "title", "severity", "owner", "actions", "step", "delay_hours", "reason", "customer_id", "forecast_next_arr_cny", "renewal_probability", "risk_level"
    ],
    "云回答样例占位",
    {
      loader: loadCloudSampleAgentAnswers,
      displayColumns: [["sample_group", "样例分组"], ["title", "标题"], ["recommended_plan", "推荐套餐"], ["explanation", "解释"], ["risk_level", "风险等级"]],
      debugFields: ["sample_id", "sample_group", "severity", "owner"],
    },
  ),
  cloud_source_refs: cloudResource(
    "cloud_source_refs.json",
    ["source_ref_id", "title", "url", "provider", "captured_at", "facts"],
    "云商品来源引用",
    { displayColumns: [["source_ref_id", "来源ID"], ["title", "标题"], ["provider", "来源类型"], ["url", "链接"], ["captured_at", "采集时间"]] },
  ),
};

export const CLOUD_FIELD_LABELS: FieldLabels = {
  product_id: "产品ID",
  product_code: "产品代码",
  product_name: "产品名称",
  provider: "云厂商",
  product_category: "产品分类",
  lifecycle_status: "生命周期",
  offer_id: "Offer ID",
  offer_name: "Offer名称",
  billing_mode: "计费模式",
  purchase_mode: "购买模式",
  sku_id: "SKU ID",
  sku_name: "SKU名称",
  sku_family: "规格族",
  status: "状态",
  meter_id: "计费项ID",
  meter_name: "计费项",
  unit_price: "单价",
  region_id: "地域ID",
  customer_id: "客户ID",
  customer_name: "客户名称",
  tier: "客户等级",
  budget_cny: "预算",
  contract_id: "合同ID",
  contract_name: "合同名称",
  effective_date: "生效日期",
  expire_date: "到期日期",
  discount_policy: "折扣策略",
  invoice_title: "发票抬头",
  subscription_id: "订购ID",
  order_id: "订单ID",
  order_status: "订单状态",
  payment_status: "支付状态",
  total_amount_cny: "订单金额",
  invoice_id: "发票ID",
  billing_month: "账期",
  amount_cny: "金额",
  dispute_amount_cny: "争议金额",
  dispute_reason: "争议原因",
  hold_reason: "暂停原因",
  release_request_id: "发布申请ID",
  change_type: "变更类型",
  rollback_plan: "回滚方案",
  approval_task_id: "审批任务ID",
  approver_role: "审批角色",
  assignee: "审批人",
  reason: "原因",
  severity: "严重度",
  risk_type: "风险类型",
  risk_signal_id: "风险ID",
  title: "标题",
  detected_at: "发现时间",
  recommended_actions: "建议动作",
  owner_team: "负责团队",
  owner_user_id: "负责人",
  owner: "负责人",
  requested_by: "申请人",
  task_id: "任务ID",
  workflow_id: "流程ID",
  linked_release_request_id: "关联发布申请",
  step: "流程环节",
  submitted_at: "提交时间",
  due_at: "截止时间",
  completed_at: "完成时间",
  sla_hours: "SLA小时",
  delay_hours: "延迟小时",
  blocker_reason: "阻塞原因",
  impact: "影响",
  renewal_id: "续约ID",
  renewal_due_date: "续约日期",
  current_arr_cny: "当前ARR",
  forecast_next_arr_cny: "预测下一期ARR",
  renewal_probability: "续约概率",
  risk_level: "风险等级",
  risk_reasons: "风险原因",
  metric_id: "指标ID",
  period: "周期",
  as_of_date: "统计日期",
  metric_group: "指标分组",
  metric_name: "指标名称",
  metric_value: "指标值",
  unit: "单位",
  compare_period: "对比周期",
  compare_value: "对比值",
  change_rate: "变化率",
  insight: "洞察",
  source_type: "来源类型",
  confidence: "置信度",
  mocked: "Demo假设",
  source_ref_ids: "来源引用",
  product_family_id: "产品族ID",
  console_url: "控制台链接",
  docs_url: "文档链接",
  offer_code: "Offer代码",
  renewal_supported: "支持续费",
  refund_supported: "支持退款",
  resize_supported: "支持变配",
  sku_code: "SKU代码",
  spec_id: "规格ID",
  spec_key: "规格键",
  spec_name: "规格名称",
  spec_value: "规格值",
  spec_unit: "规格单位",
  value_type: "值类型",
  required_for_purchase: "购买必填",
  meter_code: "计费项代码",
  meter_unit: "计量单位",
  metering_granularity: "计量粒度",
  billing_dimension: "计费维度",
  region_code: "地域代码",
  region_name: "地域名称",
  country: "国家/区域",
  availability_zone_count: "可用区数量",
  supported_product_codes: "支持产品代码",
  family_id: "产品族ID",
  family_name: "产品族名称",
  category: "分类",
  description: "说明",
  industry: "行业",
  account_owner: "客户负责人",
  cost_center_ids: "成本中心",
  account_id: "账户ID",
  account_type: "账户类型",
  display_name: "展示名称",
  parent_account_id: "父账户ID",
  start_at: "开始时间",
  end_at: "结束时间",
  renewal_status: "续约状态",
  created_at: "创建时间",
  order_item_id: "订单明细ID",
  quantity: "数量",
  source_metering_record_ids: "来源计量记录",
  evidence: "证据",
  linked_entities: "关联对象",
  source_ref_id: "来源ID",
  url: "链接",
  captured_at: "采集时间",
  retrieved_at: "检索时间",
  summary: "摘要",
  facts: "事实摘录",
  metering_record_id: "计量记录ID",
  measured_at: "计量时间",
  source: "来源系统",
  name: "名称",
  grain: "统计粒度",
  formula: "公式",
  source_entities: "来源实体",
  boss_relevance: "老板视角价值",
  snapshot_id: "快照ID",
  dimensions: "维度",
  value: "数值",
  trend: "趋势",
  estimator_id: "估算器ID",
  estimator_type: "估算类型",
  input_params_schema: "输入参数",
  assumptions: "估算假设",
  caveat: "边界说明",
  checkpoint_id: "检查点ID",
  stage: "阶段",
  checkpoint_name: "检查点",
  gap: "缺口",
  next_action: "下一步动作",
  asset_id: "材料ID",
  asset_type: "材料类型",
  audience: "面向角色",
  content: "内容",
  not_to_commit: "不可承诺项",
  capacity_pool_id: "容量池ID",
  total_gpu_cards: "GPU总卡数",
  reserved_gpu_cards: "已预留GPU卡数",
  available_gpu_cards: "可用GPU卡数",
  peak_commitment_ratio: "峰值覆盖率",
  health_status: "健康度",
  sales_policy: "销售策略",
  opportunity_id: "商机ID",
  product_ids: "产品组合",
  probability: "成交概率",
  expected_close_month: "预计成交月份",
  decision_maker: "决策人",
  region_preference: "地域偏好",
  requirements: "需求",
  blockers: "阻塞项",
  recommended_solution: "推荐方案",
  weighted_pipeline_cny: "加权商机金额",
  incident_id: "事件ID",
  started_at: "开始时间",
  expected_recovery_at: "预计恢复时间",
  affected_order_ids: "影响订单",
  affected_customer_ids: "影响客户",
  impact_gmv_cny: "影响GMV",
  revenue_recognition_risk_cny: "收入确认风险",
  customer_impact: "客户影响",
  root_cause: "根因",
  mitigation_steps: "缓解措施",
  simulation_id: "模拟ID",
  input: "输入",
  output: "输出",
  evidence_refs: "证据引用",
  risk_rule_id: "风险规则ID",
  rule_name: "规则名称",
  target_table: "适用对象",
  suggested_action: "建议动作",
  assumption_profile_id: "假设口径ID",
  applies_to_products: "适用产品",
  ai_model_id: "AI模型ID",
  model_name: "模型名称",
  modality: "模态",
  input_unit: "输入单位",
  output_unit: "输出单位",
  max_context: "最大上下文",
  supported_scenarios: "适用场景",
  scenario_id: "场景ID",
  persona: "角色",
  user_question: "用户问题",
  scenario_type: "场景类型",
  expected_output: "预期展示",
  playbook_id: "策略ID",
  route: "建议路由",
  must_include: "必须包含",
  example_answer: "示例回答",
  required_fields: "必含字段",
  forbidden_behavior: "禁止行为",
  sample_id: "样例ID",
  sample_group: "样例分组",
  question: "问题",
  answer: "回答",
  quality_notes: "质量备注",
  estimated_rounds: "预计对话轮数",
  effective_afp: "有效AFP额度",
  estimated_afp_per_round: "预计每轮AFP消耗",
  recommended_plan: "推荐套餐",
  explanation: "解释",
  estimated_video_seconds: "预计视频秒数",
  estimated_video_count_5s: "预计5秒视频条数",
  unit_cost_per_second_cny: "每秒单位成本",
  token_cost_cny: "Token成本",
  storage_cdn_cost_estimate_cny: "存储和分发成本估算",
  safety_buffer_cny: "安全缓冲金额",
  actions: "处理动作",
  review_id: "产品化评审ID",
  capability_name: "能力名称",
  capability_stage: "能力阶段",
  overall_status: "总体状态",
  readiness_score: "就绪度",
  target_customers: "目标客户",
  value_proposition: "客户价值",
  deliverables: "产品定义交付物",
  boundary_items: "能力边界",
  cost_inputs: "成本输入",
  sla_draft: "SLA初稿",
  rule_id: "权益规则ID",
  entitlement_name: "权益名称",
  grant_rule: "发放规则",
  consume_order: "消耗顺序",
  expiry_rule: "过期规则",
  unsubscribe_rule: "退订规则",
  refund_rule: "退款规则",
  overage_policy: "超额策略",
  confirmation_required: "是否需要二次确认",
  billing_explanation: "账单解释",
  matrix_id: "发布矩阵ID",
  channel: "渠道",
  channel_purpose: "渠道目的",
  visible_fields: "可展示字段",
  hidden_fields: "禁展示字段",
  source_of_truth: "数据源头",
  publication_status: "发布状态",
  precheck: "发布前检查",
  boundary_note: "边界说明",
  gate_id: "门禁ID",
  gate_name: "门禁名称",
  metric: "观察指标",
  threshold: "门禁阈值",
  risk_if_missing: "缺失风险",
  rollback_trigger: "回滚触发条件",
  customer_notice: "客户通知口径",
  lineage_id: "血缘ID",
  entity_name: "业务实体",
  field_name: "字段名",
  business_label: "业务字段名",
  owner_system: "归属系统",
  owner_role: "归属角色",
  downstream_systems: "下游系统",
  consumed_by: "消费场景",
  change_risk: "变更风险",
  change_impact: "变更影响",
  required_checks: "必做检查",
  policy_id: "财务口径ID",
  policy_name: "财务口径名称",
  commercial_model: "商业模式",
  revenue_recognition: "收入确认",
  cost_allocation: "成本归集",
  deferred_revenue_rule: "递延收入规则",
  discount_stack_rule: "折扣叠加规则",
  gross_margin_floor: "毛利底线",
  approval_required_when: "审批触发条件",
  plain_answer: "客户友好解释",
  must_disclose: "必须披露",
  change_id: "变更ID",
  current_version: "当前版本",
  target_version: "目标版本",
  change_summary: "变更摘要",
  affected_entities: "影响实体",
  affected_customers: "影响客户",
  contract_compatibility: "合同兼容性",
  channel_sync_required: "需同步渠道",
  approval_status: "审批状态",
  check_id: "巡检ID",
  check_window: "巡检窗口",
  check_area: "巡检域",
  check_item: "检查项",
  finding: "巡检发现",
};

const CLOUD_RESOURCE_DESCRIPTIONS: Record<string, string> = {
  cloud_products: "云产品主数据，描述可被商品化和售卖的云产品能力。",
  cloud_offers: "云商品 Offer，描述产品面向客户售卖的购买形态、计费模式和权益边界。",
  cloud_skus: "云商品 SKU，描述 Offer 下可售卖的具体规格包或套餐。",
  cloud_specs: "云商品规格维度，描述购买页、交付和计费需要使用的规格字段。",
  cloud_meters: "云商品计费项，描述用量如何被计量并映射到账单。",
  cloud_prices: "云商品价格规则，描述 SKU、计费项、地域和价格之间的关系。",
  cloud_regions: "云地域，描述可售卖地域、可用区和产品支持范围。",
  cloud_product_families: "云产品族，描述产品归属的业务分类和组合边界。",
  cloud_customers: "云企业客户，描述客户基础信息、行业、预算和负责人。",
  cloud_accounts: "云客户账户，描述客户在云平台里的账户层级、预算和归属关系。",
  cloud_contracts: "云客户合同，描述客户合同、有效期、折扣策略和开票信息。",
  cloud_subscriptions: "云订购关系，描述客户购买后形成的订阅、有效期和续约状态。",
  cloud_orders: "云商品订单，描述客户下单、支付和订单金额。",
  cloud_order_items: "云订单明细，描述订单中具体 Offer/SKU 的购买数量和金额。",
  cloud_bills: "云账单，描述客户账期金额、争议状态和用量来源。",
  cloud_invoices: "云发票，描述账单对应的发票状态、金额和暂停原因。",
  cloud_release_requests: "云商品发布申请，描述上架、变更、回滚和审批状态。",
  cloud_approval_tasks: "云商品审批任务，描述发布申请上的审批角色、处理人和原因。",
  cloud_risk_signals: "云商品风险信号，描述经营、价格、流程、续约、容量等风险。",
  cloud_workflow_tasks: "云商品流程任务，描述跨 PM、财务、法务、SRE、GTM 的协作节点。",
  cloud_metering_records: "云用量计量记录，描述订阅产生的用量、计量时间和来源系统。",
  cloud_renewal_opportunities: "云客户续约机会，描述续约金额、概率、风险原因和跟进动作。",
  cloud_operating_metrics: "云商品经营指标，描述 GMV、净收入、毛利、客户、争议和流程健康度。",
  cloud_metric_definitions: "云经营指标定义，描述指标口径、计算公式、来源实体和老板视角价值。",
  cloud_metric_snapshots: "云经营指标快照，描述特定周期和维度下的经营指标数值。",
  cloud_usage_estimators: "云商品估算器，描述预算、用量和产出之间的估算公式与边界。",
  cloud_ipd_checkpoints: "云商品 IPD 检查点，描述产品化、商品化、财务、SLA、容量和 GTM 门禁。",
  cloud_productization_reviews: "云产品化定义评审，描述一个技术能力变成合格产品前需要完成的目标客户、边界、成本、SLA 和交付物定义。",
  cloud_gtm_assets: "云商品 GTM 材料，描述销售话术、FAQ、目标客户和不可承诺边界。",
  cloud_entitlement_rules: "云套餐权益规则，描述 Plan 型商品的额度发放、消耗、过期、退订、退款、超额和账单解释。",
  cloud_channel_publication_matrix: "云商品渠道发布矩阵，描述官网、控制台、销售报价、API/Marketplace 等渠道展示字段和禁展示项。",
  cloud_sre_readiness_gates: "云商品 SRE 上架门禁，描述容量、限流、告警、灰度、回滚、SLA 和客户通知等稳定性检查。",
  cloud_capacity_pools: "云商品容量池，描述地域容量、可用资源、健康度和销售限制。",
  cloud_sales_opportunities: "云商品销售商机，描述客户预算、阶段、产品组合、阻塞和下一步。",
  cloud_sla_incidents: "云商品 SLA/运维事件，描述故障、延期、影响订单、GMV 和回滚方案。",
  cloud_cost_simulations: "云商品成本模拟，描述估算器输入、输出、证据和置信度。",
  cloud_risk_rules: "云风险规则，描述触发风险识别的业务规则和建议动作。",
  cloud_assumption_profiles: "云估算假设口径，描述估算、报价和演示数据的假设边界。",
  cloud_ai_models: "AI 模型目录，描述云 AI 商品依赖的模型、模态和输入输出单位。",
  cloud_demo_scenarios: "云商品演示场景，描述多角色演示问题和预期展示。",
  cloud_answer_playbooks: "云回答策略样例，描述不同角色问题的回答组织方式和必含信息。",
  cloud_data_contracts: "云数据回答契约，描述回答时必须包含的信息和禁止行为。",
  cloud_sample_agent_answers: "云回答样例占位，预留用于沉淀高质量样例回答。",
  cloud_master_data_lineage: "云主数据血缘，描述主数据字段的归属系统、维护角色、下游消费和变更影响。",
  cloud_financial_commercial_policies: "云商品财务商业化口径，描述收入确认、成本归集、递延收入、折扣叠加和毛利底线。",
  cloud_customer_explanation_playbooks: "云客户解释话术，描述客户买前/买后解释、可见字段、必须披露和下一步动作。",
  cloud_product_change_versions: "云商品版本变更，描述 SKU、套餐、权益、价格、地域和 SLA 等变更影响、审批和回滚。",
  cloud_post_launch_checks: "云商品发布后巡检，描述发布后官网、控制台、订单、计量、账单和客户反馈检查。",
  cloud_source_refs: "云商品来源引用，描述演示数据、公开资料和假设事实的来源。",
};

const CLOUD_RESOURCE_FIELD_EXTENSIONS: Record<string, string[]> = {
  cloud_contracts: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_subscriptions: ["source_type", "mocked", "confidence"],
  cloud_orders: ["source_type", "mocked", "confidence"],
  cloud_bills: ["source_type", "mocked", "confidence", "source_ref_ids", "dispute_amount_cny", "dispute_reason", "owner_user_id"],
  cloud_invoices: ["source_type", "mocked", "confidence", "hold_reason"],
  cloud_release_requests: ["source_type", "mocked", "confidence"],
  cloud_risk_signals: ["source_type", "confidence", "source_ref_ids"],
  cloud_workflow_tasks: ["source_ref_ids", "source_type"],
  cloud_productization_reviews: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_entitlement_rules: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_channel_publication_matrix: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_sre_readiness_gates: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_master_data_lineage: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_financial_commercial_policies: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_customer_explanation_playbooks: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_product_change_versions: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_post_launch_checks: ["source_type", "mocked", "confidence", "source_ref_ids"],
  cloud_demo_scenarios: ["stage", "release_request_id", "source_type", "mocked", "confidence"],
  cloud_source_refs: ["source_type", "retrieved_at", "summary", "mocked", "confidence"],
};

const CLOUD_FIELD_DESCRIPTIONS: Record<string, string> = {
  product_id: "云产品的内部唯一标识，用于关联 Offer、SKU、价格、容量和经营指标。",
  product_code: "云产品对外或半对外的产品代码，用于识别 ECS、RDS、TOS 等产品能力。",
  product_name: "用户可理解的云产品名称。",
  provider: "演示数据来源的云厂商，仅用于 demo dataset，不代表当前 Agent 绑定单一厂商。",
  product_family_id: "产品所属产品族，用于做产品组合、经营分类和售卖边界管理。",
  product_category: "产品业务分类，例如计算、存储、AI、网络等。",
  lifecycle_status: "产品生命周期状态，用于判断是否可售卖、灰度或下线。",
  console_url: "产品控制台入口链接，演示时仅作为参考信息。",
  docs_url: "产品文档入口链接，演示时仅作为参考信息。",
  source_ref_ids: "支撑该记录的来源引用，用于追溯公开资料、演示假设或内部样例。",
  offer_id: "商品 Offer 的唯一标识，用于关联购买形态、SKU 和计费项。",
  offer_code: "Offer 代码，用于商品化配置和报价识别。",
  offer_name: "Offer 的业务名称，通常代表一个可购买的商品形态。",
  billing_mode: "计费模式，例如按量、包月、资源包或订阅。",
  purchase_mode: "购买方式，例如自助购买、销售协助或合同制购买。",
  renewal_supported: "是否支持续费。",
  refund_supported: "是否支持退款。",
  resize_supported: "是否支持升降配或规格变更。",
  sku_id: "SKU 的唯一标识，用于关联规格、价格和订单明细。",
  sku_code: "SKU 代码，用于售卖配置和报价识别。",
  sku_name: "SKU 的业务名称，描述客户实际购买的规格或套餐。",
  sku_family: "SKU 所属规格族，用于容量、成本和售卖策略归类。",
  status: "当前业务状态，展示时应转写为中文状态。",
  spec_id: "规格字段的唯一标识。",
  spec_key: "规格字段的底层键名，前台应优先展示规格名称。",
  spec_name: "规格字段的中文业务名称。",
  spec_value: "规格字段的值。",
  spec_unit: "规格字段的单位。",
  value_type: "规格值的数据类型。",
  required_for_purchase: "购买时是否必须填写或确认该规格字段。",
  meter_id: "计费项唯一标识，用于连接用量、价格和账单。",
  meter_code: "计费项代码，用于计量系统和价格规则识别。",
  meter_name: "计费项的业务名称。",
  meter_unit: "计费项的计量单位。",
  metering_granularity: "用量采集或结算粒度。",
  billing_dimension: "计费维度，例如实例、请求、时长、流量或视频秒数。",
  price_id: "价格规则唯一标识。",
  currency: "币种。",
  price_type: "价格类型，例如目录价、促销价、合同价或估算价。",
  unit_price: "单价，必须结合计费项、单位和价格类型理解。",
  pricing_rule: "价格生效、阶梯、折扣或资源包规则说明。",
  region_id: "地域唯一标识，用于关联容量、价格和销售范围。",
  region_code: "地域代码。",
  region_name: "地域中文名称。",
  country: "地域所在国家或区域。",
  availability_zone_count: "该地域可用区数量。",
  supported_product_codes: "该地域支持售卖或交付的产品代码列表。",
  customer_id: "客户唯一标识，用于权限隔离、账单、合同和续约关联。",
  customer_name: "客户名称。",
  industry: "客户所在行业，用于方案推荐和 GTM 分层。",
  tier: "客户等级或重要性分层。",
  account_owner: "客户归属负责人。",
  budget_cny: "客户预算金额，单位为人民币。",
  cost_center_ids: "客户成本中心或内部核算单元。",
  account_id: "云账户唯一标识。",
  account_type: "账户类型，例如主账号、子账号或项目账号。",
  display_name: "账户对业务用户展示的名称。",
  parent_account_id: "父级账户标识，用于账户层级关系。",
  contract_id: "合同唯一标识。",
  contract_name: "合同名称。",
  effective_date: "合同生效日期。",
  expire_date: "合同到期日期。",
  discount_policy: "合同或客户可使用的折扣策略，不能直接理解为销售可承诺折扣。",
  invoice_title: "开票抬头。",
  subscription_id: "订购关系唯一标识。",
  order_id: "订单唯一标识。",
  order_status: "订单业务状态。",
  payment_status: "支付状态。",
  created_at: "订单创建时间。",
  total_amount_cny: "订单总金额，单位为人民币。",
  order_item_id: "订单明细唯一标识。",
  quantity: "购买数量或用量数量。",
  amount_cny: "金额，单位为人民币。",
  bill_id: "账单唯一标识。",
  billing_month: "账单所属月份。",
  source_metering_record_ids: "形成账单金额的计量记录引用。",
  dispute_amount_cny: "存在争议的账单金额，单位为人民币。",
  dispute_reason: "账单争议原因。",
  invoice_id: "发票唯一标识。",
  hold_reason: "发票暂停或挂起原因。",
  source_type: "数据来源性质，例如演示数据、估算假设或公开参考。",
  mocked: "是否为演示或模拟数据，展示时必须说明为演示数据。",
  confidence: "数据或估算的置信度，展示时应提示是否需要人工复核。",
  release_request_id: "商品发布或变更申请唯一标识。",
  change_type: "发布申请的变更类型。",
  requested_by: "发布申请发起人。",
  rollback_plan: "发布失败或风险触发时的回滚方案。",
  approval_task_id: "审批任务唯一标识。",
  approver_role: "审批角色，例如财务、法务、SRE 或业务负责人。",
  assignee: "审批任务处理人。",
  reason: "审批、暂停或处理原因。",
  risk_signal_id: "风险信号唯一标识。",
  risk_type: "风险类别，例如价格、容量、流程、续约或账单风险。",
  title: "业务标题。",
  severity: "风险严重度，展示时应转写为高/中/低风险。",
  linked_entities: "风险关联的产品、客户、订单、发布申请等业务对象。",
  evidence: "支撑风险判断的证据摘要。",
  detected_at: "风险发现时间。",
  owner_team: "负责处理该事项的团队。",
  owner_user_id: "负责处理该事项的业务负责人或接口人。",
  recommended_actions: "建议采取的业务动作。",
  task_id: "流程任务唯一标识。",
  workflow_id: "流程唯一标识。",
  linked_release_request_id: "流程任务关联的发布申请。",
  step: "流程环节名称。",
  submitted_at: "任务提交时间。",
  due_at: "任务截止时间。",
  completed_at: "任务完成时间。",
  sla_hours: "约定处理时长，单位为小时。",
  delay_hours: "已延期时长，单位为小时。",
  blocker_reason: "流程阻塞原因。",
  impact: "阻塞对发布、客户、收入或经营目标的影响。",
  metric_name: "经营指标名称。",
  metric_value: "经营指标数值。",
  metric_group: "指标分组，例如收入、毛利、客户、流程或风险。",
  compare_period: "对比周期。",
  compare_value: "对比周期数值。",
  change_rate: "相较对比周期的变化率。",
  insight: "指标背后的业务解读。",
  next_action: "下一步业务动作。",
  risk_level: "风险等级，展示时应转写为中文风险级别。",
  renewal_probability: "续约概率。",
  current_arr_cny: "当前年度经常性收入，单位为人民币。",
  forecast_next_arr_cny: "预测下一期年度经常性收入，单位为人民币。",
  risk_reasons: "续约或经营风险原因。",
  formula: "计算或估算公式。",
  assumptions: "估算使用的关键假设。",
  caveat: "估算、报价或演示数据的边界说明。",
  review_id: "产品化评审记录唯一标识。",
  capability_name: "准备商品化的底层产品能力或技术能力名称。",
  capability_stage: "能力当前成熟度阶段，用于判断是否已经具备产品化条件。",
  overall_status: "整体评审状态，展示时应转写为待补定义、已阻塞、处理中或可继续推进。",
  readiness_score: "产品化或上架门禁的就绪度评分，通常按百分比理解。",
  target_customers: "该商品优先服务的目标客户或目标行业分层。",
  value_proposition: "该能力被包装成商品后对客户产生的业务价值。",
  deliverables: "产品定义过程中需要沉淀的交付物，例如目标客户、能力边界、成本输入、SLA 初稿和购买页字段。",
  boundary_items: "销售、官网、控制台和合同里不能承诺或需要明确说明的能力边界。",
  cost_inputs: "财务测算和毛利复核需要的成本输入项。",
  sla_draft: "SRE 和法务共同确认前的 SLA 文案草稿。",
  rule_id: "权益规则唯一标识。",
  entitlement_name: "套餐或资源包权益的业务名称。",
  grant_rule: "权益如何发放给客户。",
  consume_order: "客户使用时各类额度或资源包的消耗优先级。",
  expiry_rule: "权益、资源包或赠送额度的过期口径。",
  unsubscribe_rule: "客户退订时权益如何停止、冻结或清算。",
  refund_rule: "客户退款时如何处理未消耗和已消耗权益。",
  overage_policy: "额度用完后的超额付费、确认和预算上限策略。",
  confirmation_required: "是否必须由客户或内部负责人二次确认后才能生效。",
  billing_explanation: "面向客户解释账单、额度和用量消耗的业务口径。",
  matrix_id: "渠道发布矩阵记录唯一标识。",
  channel: "商品信息要发布到的渠道，例如官网、控制台、销售报价或 API/Marketplace。",
  channel_purpose: "该渠道在获客、购买、报价或开发者接入中的作用。",
  visible_fields: "该渠道允许展示给客户或销售的业务字段。",
  hidden_fields: "该渠道不应展示的内部成本、阈值、未审批价格或灰度策略。",
  source_of_truth: "该渠道展示内容应以哪个系统或业务实体为准。",
  publication_status: "渠道发布准备状态，展示时应转写为可发布、需复核或被阻塞。",
  precheck: "发布到该渠道前必须完成的业务检查。",
  boundary_note: "帮助用户理解渠道角色、数据边界和不可承诺项的说明。",
  gate_id: "SRE 上架门禁唯一标识。",
  gate_name: "SRE 需要确认的稳定性门禁名称。",
  metric: "门禁观察的核心技术或业务指标。",
  threshold: "指标达到什么条件才允许发布或继续放量。",
  risk_if_missing: "如果缺失该门禁，会对客户、交付、收入或运营造成什么风险。",
  rollback_trigger: "触发回滚、限流、下线或转人工处理的条件。",
  customer_notice: "风险发生时对客户、客服或销售的统一沟通口径。",
  lineage_id: "主数据血缘记录唯一标识。",
  entity_name: "被治理的业务实体名称，例如 Offer、SKU、权益或地域。",
  field_name: "底层字段名，前台应优先展示业务字段名。",
  business_label: "面向业务用户展示的字段名称。",
  owner_system: "负责维护该字段的主数据系统或业务系统。",
  owner_role: "对该字段业务口径负责的角色或团队。",
  downstream_systems: "消费该字段的下游系统列表。",
  consumed_by: "字段在下游被用于哪些业务场景。",
  change_risk: "字段变更风险等级。",
  change_impact: "字段变更会影响哪些业务对象或流程。",
  required_checks: "变更该字段前必须完成的检查项。",
  policy_id: "财务商业化口径唯一标识。",
  policy_name: "财务商业化口径的业务名称。",
  commercial_model: "商品商业模式，例如按量、订阅、资源包或合同折扣。",
  revenue_recognition: "收入确认口径。",
  cost_allocation: "成本归集和分摊口径。",
  deferred_revenue_rule: "预付、资源包或包月收入的递延确认规则。",
  discount_stack_rule: "合同折扣、促销、资源包和赠送权益能否叠加的规则。",
  gross_margin_floor: "低于该毛利底线时需要审批或暂停自动生效。",
  approval_required_when: "触发财务或业务审批的条件。",
  plain_answer: "面向客户的友好解释文本。",
  must_disclose: "回答客户时必须披露的边界或风险。",
  change_id: "商品版本或配置变更唯一标识。",
  current_version: "当前生效或演示中的商品版本。",
  target_version: "计划变更到的目标版本。",
  change_summary: "变更内容摘要。",
  affected_entities: "该变更影响的主数据、合同、账单、渠道或客户对象。",
  affected_customers: "该变更可能影响的客户范围。",
  contract_compatibility: "变更对存量合同和续约合同的兼容性说明。",
  channel_sync_required: "需要同步更新的渠道或触点。",
  approval_status: "变更审批状态。",
  check_id: "发布后巡检记录唯一标识。",
  check_window: "巡检时间窗口，例如发布后 24 小时。",
  check_area: "巡检关注域，例如渠道一致性、订单计量账单闭环。",
  check_item: "具体巡检事项。",
  finding: "巡检发现的问题或结论。",
};

function inferCloudFieldType(field: string): string {
  if (/(_ids|supported_|requirements|blockers|actions|steps|refs|entities|scenarios|assumptions|fields|behavior|facts)$/.test(field)) return "array";
  if (/(_at|_date|month|period)$/.test(field)) return "string";
  if (/(amount|budget|price|value|rate|ratio|probability|confidence|count|quantity|hours|cards|context|arr|gmv|revenue|total|reserved|available|impact_)/.test(field)) return "number";
  if (/^(mocked|required_|.*_supported)$/.test(field)) return "boolean";
  return "string";
}

function fieldDescription(resource: string, config: ResourceConfig, field: string): string {
  const label = CLOUD_FIELD_LABELS[field] ?? field;
  const description = CLOUD_FIELD_DESCRIPTIONS[field] ?? `用于${config.label ?? resource}的业务识别、筛选或展示。`;
  return `${label}：${description}`;
}

function mergeFields(fields: string[], extra: string[] = []): string[] {
  return [...new Set([...fields, ...extra])];
}

function applyCloudDictionary(): void {
  for (const [resource, config] of Object.entries(CLOUD_COMMODITY_RESOURCES)) {
    config.description = config.description ?? CLOUD_RESOURCE_DESCRIPTIONS[resource] ?? `${config.label ?? resource}的业务数据。`;
    config.fields = mergeFields(config.fields, CLOUD_RESOURCE_FIELD_EXTENSIONS[resource]);
    config.schema = Object.fromEntries(config.fields.map((field) => [
      field,
      {
        type: inferCloudFieldType(field),
        description: fieldDescription(resource, config, field),
      }
    ]));
  }
}

applyCloudDictionary();

export const CLOUD_QUERY_SCHEMAS = Object.fromEntries(
  Object.entries(CLOUD_COMMODITY_RESOURCES).map(([resource, config]) => [
    resource,
    {
      entity: resource.replace(/^cloud_/, "cloud_commodity_"),
      label: config.label,
      description: config.description,
      fields: config.fields,
      fieldMetadata: config.schema,
      defaultFields: (config.displayColumns?.map(([field]) => field) ?? config.fields).slice(0, 8),
      defaultSort: [] as Array<{ field: string; direction?: "asc" | "desc" }>,
    },
  ]),
);
