/**
 * Dealer 业务域资源定义。
 *
 * Dealer 域资源配置（dealer_* 系列）。
 * 数据文件路径保持不变（兼容期不迁移数据目录）。
 */

import { buildDealerMetrics } from "./dealer-metrics.js";
import type { ResourceConfig } from "../../resources/types.js";
import type { FieldLabels } from "../../resources/types.js";

type DataRow = Record<string, unknown>;

/**
 * Dealer 域资源配置。
 */
export const DEALER_RESOURCES: Record<string, ResourceConfig> = {
  dealer_stores: {
    file: "data/dealer-stores.json",
    fields: ["id", "name", "short_name", "city", "region", "store_type", "manager_user_id", "capacity", "status"],
    domain: "dealer",
    label: "经销商门店",
  },
  dealer_vehicles: {
    file: "data/dealer-vehicles.json",
    fields: ["vin", "store_id", "store_name", "series", "model", "year", "color", "source_type", "purchase_mode", "cost", "finance_interest_accrued", "landing_cost", "min_sale_price", "inbound_date", "stock_age_days", "stock_warning_level", "status", "certificate_status", "vehicle_tag", "mileage", "sales_order_id"],
    domain: "dealer",
    label: "整车库存",
    displayColumns: [
      ["store_name", "门店"],
      ["series", "车系"],
      ["model", "车型"],
      ["status", "状态"],
      ["stock_age_days", "库龄(天)"],
      ["stock_warning_level", "预警"],
    ],
    debugFields: ["vin", "store_name", "series", "model", "status", "stock_age_days", "stock_warning_level"],
    factKey: "dealer_inventory_detail",
    rowTemplate: (row: DataRow) => {
      const stockAge = row.stock_age_days != null ? `库龄 ${row.stock_age_days} 天` : "";
      const warning = row.stock_warning_level ? `预警 ${row.stock_warning_level}` : "";
      return `- ${row.store_name ?? ""} ${row.series ?? ""} ${row.model ?? ""}（${[stockAge, warning].filter(Boolean).join("，")}）`;
    },
    schema: {
      vin: "VIN码",
      store_name: "门店名称",
      series: "车系",
      model: "车型",
      year: "年款",
      color: "颜色",
      source_type: "来源类型",
      purchase_mode: "进车方式",
      cost: { type: "number", description: "成本" },
      landing_cost: { type: "number", description: "综合落地成本" },
      inbound_date: { type: "date", description: "入库日期" },
      stock_age_days: { type: "number", description: "库龄天数" },
      stock_warning_level: { type: "string", description: "库龄预警", enum: ["正常", "关注", "预警", "紧急"] },
      status: "状态",
      certificate_status: "合格证状态",
    },
  },
  dealer_inbounds: {
    file: "data/dealer-inbounds.json",
    fields: ["id", "store_id", "store_name", "order_type", "series", "model", "color", "customer_name", "sales_consultant_id", "byd_order_no", "status", "expected_arrival_date", "customer_promised_date", "deposit_amount"],
    domain: "dealer",
    label: "在途订单",
    debugFields: ["id", "store_name", "series", "model", "status", "expected_arrival_date"],
    schema: {
      id: "在途单号",
      store_name: "门店名称",
      order_type: "订单类型",
      series: "车系",
      model: "车型",
      color: "颜色",
      customer_name: "客户姓名",
      status: "状态",
      expected_arrival_date: { type: "date", description: "预计到店日期" },
      customer_promised_date: { type: "date", description: "客户承诺交期" },
    },
  },
  dealer_quotas: {
    file: "data/dealer-quotas.json",
    fields: ["id", "store_id", "store_name", "month", "series", "model", "color", "quota_total", "bound_inbound_count", "available_quota"],
    domain: "dealer",
    label: "配额记录",
    debugFields: ["id", "store_name", "month", "series", "quota_total", "available_quota"],
    schema: {
      id: "配额ID",
      store_name: "门店名称",
      month: "月份",
      series: "车系",
      model: "车型",
      quota_total: { type: "number", description: "总配额" },
      bound_inbound_count: { type: "number", description: "已绑定在途" },
      available_quota: { type: "number", description: "剩余配额" },
    },
  },
  dealer_leads: {
    file: "data/dealer-leads.json",
    fields: ["id", "customer_name", "phone_masked", "source", "campaign", "store_id", "store_name", "owner_user_id", "owner_name", "interested_series", "intention_level", "status", "created_at", "assigned_at", "first_contact_at", "last_followup_at", "followup_count", "visit_count", "expected_purchase_date", "lost_reason", "converted_order_id"],
    domain: "dealer",
    label: "销售线索",
    displayColumns: [
      ["store_name", "门店"],
      ["customer_name", "客户"],
      ["source", "来源"],
      ["interested_series", "意向车系"],
      ["intention_level", "意向等级"],
      ["status", "状态"],
      ["followup_count", "跟进次数"],
    ],
    debugFields: ["id", "customer_name", "store_name", "interested_series", "intention_level", "status", "followup_count"],
    factKey: "dealer_lead_detail",
    rowTemplate: (row: DataRow) => {
      return `- [${row.id ?? ""}] ${row.store_name ?? ""} ${row.customer_name ?? ""} ${row.interested_series ?? ""}（意向 ${row.intention_level ?? ""}，状态 ${row.status ?? ""}，跟进 ${row.followup_count ?? 0} 次）`;
    },
    schema: {
      id: "线索编号",
      customer_name: "客户姓名",
      source: "来源",
      store_name: "门店名称",
      owner_name: "负责人",
      interested_series: "意向车系",
      intention_level: { type: "string", description: "意向等级", enum: ["H", "A", "B", "C"] },
      status: { type: "string", description: "状态", enum: ["待首次联系", "跟进中", "已到店", "已成交", "战败"] },
      created_at: { type: "date", description: "创建时间" },
      followup_count: { type: "number", description: "跟进次数" },
      visit_count: { type: "number", description: "到店次数" },
    },
  },
  dealer_sales_orders: {
    file: "data/dealer-sales-orders.json",
    fields: ["id", "store_id", "store_name", "customer_name", "owner_user_id", "owner_name", "vin", "series", "model", "order_type", "order_status", "payment_status", "invoice_status", "delivery_status", "list_price", "final_price", "landing_cost", "gross_profit", "deposit_amount", "paid_amount", "finance_amount", "created_at", "expected_delivery_date"],
    domain: "dealer",
    label: "销售订单",
    displayColumns: [
      ["store_name", "门店"],
      ["customer_name", "客户"],
      ["series", "车系"],
      ["model", "车型"],
      ["order_status", "订单状态"],
      ["payment_status", "收款状态"],
      ["delivery_status", "交付状态"],
      ["final_price", "成交价"],
    ],
    debugFields: ["id", "store_name", "customer_name", "series", "order_status", "payment_status", "delivery_status", "final_price"],
    factKey: "dealer_order_detail",
    rowTemplate: (row: DataRow) => {
      return `- [${row.id ?? ""}] ${row.store_name ?? ""} ${row.customer_name ?? ""} ${row.series ?? ""} ${row.model ?? ""}（${row.order_status ?? ""}/${row.payment_status ?? ""}/${row.delivery_status ?? ""}，${row.final_price ?? ""}）`;
    },
    schema: {
      id: "订单编号",
      store_name: "门店名称",
      customer_name: "客户姓名",
      owner_name: "负责人",
      series: "车系",
      model: "车型",
      order_type: "订单类型",
      order_status: "订单状态",
      payment_status: "收款状态",
      invoice_status: "开票状态",
      delivery_status: "交付状态",
      list_price: { type: "number", description: "指导价" },
      final_price: { type: "number", description: "成交价" },
      gross_profit: { type: "number", description: "毛利" },
      created_at: { type: "date", description: "创建时间" },
      expected_delivery_date: { type: "date", description: "预计交付日期" },
    },
  },
  dealer_finance: {
    file: "data/dealer-finance.json",
    fields: ["id", "resource_type", "store_id", "store_name", "direction", "category", "amount", "balance_after", "related_order_id", "occurred_at", "status"],
    domain: "dealer",
    label: "财务流水",
    debugFields: ["id", "store_name", "category", "direction", "amount", "status", "occurred_at"],
    factKey: "dealer_finance_detail",
    rowTemplate: (row: DataRow) => {
      return `- [${row.id ?? ""}] ${row.store_name ?? ""} ${row.category ?? ""} ${row.direction ?? ""} ${row.amount ?? ""}（${row.status ?? ""}，${row.occurred_at ?? ""}）`;
    },
    schema: {
      id: "流水编号",
      resource_type: "资金类型",
      store_name: "门店名称",
      direction: "方向",
      category: "类别",
      amount: { type: "number", description: "金额" },
      balance_after: { type: "number", description: "变动后余额" },
      occurred_at: { type: "date", description: "发生日期" },
      status: "状态",
    },
  },
  dealer_repair_orders: {
    file: "data/dealer-repair-orders.json",
    fields: ["id", "store_id", "store_name", "customer_name", "vin", "series", "service_advisor_id", "service_advisor_name", "order_type", "status", "appointment_at", "reception_at", "promised_finish_at", "labor_amount", "part_amount", "receivable_amount", "warranty_claim_id", "next_service_suggestion"],
    domain: "dealer",
    label: "售后工单",
    debugFields: ["id", "store_name", "customer_name", "series", "order_type", "status", "promised_finish_at"],
    factKey: "dealer_after_sales_detail",
    rowTemplate: (row: DataRow) => {
      return `- [${row.id ?? ""}] ${row.store_name ?? ""} ${row.series ?? ""} ${row.order_type ?? ""}（状态 ${row.status ?? ""}，承诺完工 ${row.promised_finish_at ?? ""}）`;
    },
    schema: {
      id: "工单编号",
      store_name: "门店名称",
      customer_name: "客户姓名",
      series: "车系",
      service_advisor_name: "服务顾问",
      order_type: "工单类型",
      status: "状态",
      appointment_at: { type: "date", description: "预约时间" },
      promised_finish_at: { type: "date", description: "承诺完工时间" },
      receivable_amount: { type: "number", description: "应收金额" },
    },
  },
  dealer_warranty_claims: {
    file: "data/dealer-warranty-claims.json",
    fields: ["id", "repair_order_id", "store_id", "store_name", "customer_name", "vin", "series", "fault_category", "fault_code", "claim_status", "claimed_amount", "approved_amount", "difference_amount", "submitted_at", "expected_settlement_at", "evidence_status"],
    domain: "dealer",
    label: "三包索赔",
    debugFields: ["id", "store_name", "series", "fault_category", "claim_status", "claimed_amount", "difference_amount"],
    factKey: "dealer_warranty_detail",
    rowTemplate: (row: DataRow) => {
      const diff = row.difference_amount != null ? `差额 ${row.difference_amount}` : "";
      return `- [${row.id ?? ""}] ${row.store_name ?? ""} ${row.series ?? ""} ${row.fault_category ?? ""}（${row.claim_status ?? ""}${diff ? "，" + diff : ""}，提交 ${row.submitted_at ?? ""}）`;
    },
    schema: {
      id: "索赔单号",
      repair_order_id: "维修工单号",
      store_name: "门店名称",
      series: "车系",
      fault_category: "故障类别",
      fault_code: "故障代码",
      claim_status: "索赔状态",
      claimed_amount: { type: "number", description: "申报金额" },
      approved_amount: { type: "number", description: "核准金额" },
      difference_amount: { type: "number", description: "差异金额" },
      submitted_at: { type: "date", description: "提交时间" },
      evidence_status: "证据状态",
    },
  },
  dealer_metrics: {
    loader: buildDealerMetrics,
    fields: ["id", "scope", "store_name", "category", "metric", "value", "unit", "severity", "summary", "recommendation", "related_resource", "related_ids"],
    domain: "dealer",
    label: "经营指标",
    defaultLimit: 50,
    debugFields: ["id", "scope", "store_name", "category", "metric", "value", "severity"],
    factKey: "dealer_metrics",
    rowTemplate: (row: DataRow, fieldLabels?: Record<string, string>) => {
      const categoryLabel = fieldLabels?.[String(row.category ?? "")] ?? String(row.category ?? "");
      return `- ${row.store_name ?? ""} ${categoryLabel}/${row.metric ?? ""}：${row.value ?? ""}${row.unit ?? ""}（${row.severity ?? ""}） ${row.summary ?? ""} 建议：${row.recommendation ?? ""}`;
    },
    schema: {
      id: "指标ID",
      store_name: "门店名称",
      category: "分类",
      metric: "指标名",
      value: { type: "number", description: "指标值" },
      unit: "单位",
      severity: { type: "string", description: "严重程度", enum: ["critical", "warning", "normal"] },
      summary: "摘要",
      recommendation: "建议",
    },
  },
};

/**
 * Dealer 域字段标签。
 */
export const DEALER_FIELD_LABELS: FieldLabels = {
  vin: "VIN",
  store: "门店",
  store_id: "门店ID",
  store_name: "门店",
  short_name: "门店简称",
  city: "城市",
  region: "区域",
  store_type: "门店类型",
  manager_user_id: "门店负责人",
  capacity: "库容",
  series: "车系",
  model: "车型",
  year: "年款",
  color: "颜色",
  source_type: "来源类型",
  purchase_mode: "进车方式",
  cost: "成本",
  finance_interest_accrued: "融资利息累计",
  landing_cost: "综合落地成本",
  min_sale_price: "最低售价参考",
  inbound_date: "入库日期",
  stock_age_days: "库龄天数",
  stock_warning_level: "库龄预警",
  certificate_status: "合格证状态",
  vehicle_tag: "车辆标签",
  mileage: "里程",
  sales_order_id: "销售订单",
  order_type: "订单类型",
  expected_arrival_date: "预计到店",
  customer_promised_date: "客户承诺交期",
  deposit_amount: "定金",
  month: "月份",
  quota_total: "总配额",
  bound_inbound_count: "已绑定在途",
  available_quota: "剩余配额",
  phone_masked: "手机号",
  source: "来源",
  campaign: "活动",
  owner_name: "负责人",
  interested_series: "意向车系",
  intention_level: "意向等级",
  assigned_at: "分配时间",
  first_contact_at: "首次联系",
  last_followup_at: "最近跟进",
  followup_count: "跟进次数",
  visit_count: "到店次数",
  expected_purchase_date: "预计购车",
  lost_reason: "战败原因",
  converted_order_id: "成交订单",
  order_status: "订单状态",
  payment_status: "收款状态",
  invoice_status: "开票状态",
  delivery_status: "交付状态",
  list_price: "指导价",
  final_price: "成交价",
  gross_profit: "毛利",
  paid_amount: "已收金额",
  finance_amount: "金融放款",
  expected_delivery_date: "预计交付",
  resource_type: "资金类型",
  direction: "方向",
  category: "类别",
  balance_after: "变动后余额",
  related_order_id: "关联单据",
  occurred_at: "发生日期",
  service_advisor_id: "服务顾问ID",
  service_advisor_name: "服务顾问",
  appointment_at: "预约时间",
  reception_at: "接待时间",
  promised_finish_at: "承诺完工",
  labor_amount: "工时费",
  part_amount: "配件费",
  receivable_amount: "应收金额",
  warranty_claim_id: "三包索赔单",
  next_service_suggestion: "下次服务建议",
  repair_order_id: "维修工单",
  fault_category: "故障类别",
  fault_code: "故障代码",
  claim_status: "索赔状态",
  claimed_amount: "申报金额",
  approved_amount: "核准金额",
  difference_amount: "差异金额",
  expected_settlement_at: "预计结算",
  evidence_status: "证据状态",
  scope: "范围",
  metric: "指标",
  value: "指标值",
  unit: "单位",
  severity: "严重程度",
  summary: "摘要",
  recommendation: "建议",
  related_resource: "关联资源",
  related_ids: "关联记录",
  // ── metric 名称标签（供 labelOfMetric 动态查找） ──
  total_revenue: "总成交额",
  order_count: "订单数",
  avg_price: "平均成交价",
  total_profit: "总毛利",
  gross_margin: "毛利率(%)",
  max_price: "最高成交价",
  min_price: "最低成交价",
  total_amount: "总金额",
  unsettled_amount: "未结清金额",
  record_count: "记录数",
  avg_amount: "平均金额",
  total_receivable: "应收合计",
  avg_labor: "平均工时费",
  max_receivable: "最高应收",
  total_labor: "工时费合计",
  lead_count: "线索数",
  converted_count: "成交线索数",
  conversion_rate: "转化率(%)",
  lost_count: "战败线索数",
  avg_followup: "平均跟进次数",
  // ── 分组维度标签 / 风险类型标签 ──
  inventory: "库存",
  lead: "线索",
  sales: "销售",
  finance: "财务",
  after_sales: "售后",
  warranty: "三包",
  work_order: "工单",
  claim: "索赔",
  // ── fact name 标签（供 readableFactNameFromRegistry 查找） ──
  dealer_metrics: "经营指标",
  dealer_inventory_detail: "库存明细",
  dealer_lead_detail: "线索明细",
  dealer_order_detail: "订单明细",
  dealer_finance_detail: "财务明细",
  dealer_after_sales_detail: "售后明细",
  dealer_warranty_detail: "三包索赔明细",
};
